rvm:
  - 1.9.2
  - 1.9.3
notifications:
  recipients:
    - jari.bakken@gmail.com
    - p0deje@gmail.com
  irc: "irc.freenode.net#watir"
before_script:
  - support/travis.sh
env:
  - WATIR_WEBDRIVER_BROWSER=firefox
  - WATIR_WEBDRIVER_BROWSER=firefox ALWAYS_LOCATE=false
  - WATIR_WEBDRIVER_BROWSER=firefox PREFER_CSS=1 SELECTOR_STATS=1
  - WATIR_WEBDRIVER_BROWSER=chrome
  - WATIR_WEBDRIVER_BROWSER=chrome ALWAYS_LOCATE=false
  - WATIR_WEBDRIVER_BROWSER=chrome PREFER_CSS=1 SELECTOR_STATS=1
