<%
  @path = "#{Rubber.root}/config/database.yml"
%>

# Sets up rails to talk to mysql-proxy load balancer running on localhost,
# which then then balances requests between sql nodes in the cluster
<%= Rubber.env %>:
  adapter: <%= YAML::load(File.open("#{Rubber.root}/config/database.yml"))["production"]["adapter"] %>
  encoding: utf8
  database: <%= rubber_env.db_name %>
  username: <%= rubber_env.db_user %>
  password: <%= rubber_env.db_pass %>
  host: 127.0.0.1
  port: 4040


