---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-2f610e78
  image_type: t1.micro
  image_id: ami-7d23612f
  security_groups:
  - your_app_name_production_default
  - your_app_name_production_web
  - your_app_name_production_web_tools
  - your_app_name_production_production
  - your_app_name_production_apache
  - your_app_name_production_app
  - your_app_name_production_passenger
  - your_app_name_production_collectd
  - your_app_name_production_common
  - your_app_name_production_monit
  - your_app_name_production_db
  - your_app_name_production_postgresql
  - your_app_name_production_postgresql_master
  - your_app_name_production_elasticsearch
  - your_app_name_production_examples
  - your_app_name_production_graphite_server
  - your_app_name_production_graphite_web
  - your_app_name_production_graylog_elasticsearch
  - your_app_name_production_graylog_mongodb
  - your_app_name_production_mongodb
  - your_app_name_production_graylog_server
  - your_app_name_production_graylog_web
  - your_app_name_production_haproxy
  external_host: ec2-54-251-3-29.ap-southeast-1.compute.amazonaws.com
  external_ip: 54.251.3.29
  internal_host: ip-10-128-129-70.ap-southeast-1.compute.internal
  internal_ip: 10.128.129.70
  zone: ap-southeast-1b
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
