<%
  @path = "#{Rubber.root}/config/memcached.yml"
  @additive =  ["# rubber-memcached-start", "# rubber-memcached-end"]
%>


<%= Rubber.env %>:
  memory: 256
  fragments: true
  benchmarking: false
  servers:
  <% rubber_instances.for_role('memcached').each do |ic| %>
    - <%= ic.full_name %>:11211
  <% end %>
